home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_form),
    path('logout', views.login_out),
    path('contact', views.contact_form, name='contact'),

    path('addcomment/<int:proid>', views.comment_add, name='addcomment'),
    path('deletecomment/<int:id>', views.comment_delete, name='deletecomment'),
    path('comments', views.comment_list, name='comments'),


]

order/urls.py
from django.urls import path
from . import views



app_name = 'order'

urlpatterns = [
    path('', views.index, name='index'),
    path('shopcart', views.shop_cart_list, name='shopcart'),
    path('addtocart/<int:proid>', views.shop_cart_add, name='addtocart'),
    path('deletefromcart/<int:id>', views.shop_cart_delete, name='deletefromcart'),
    path('detail/<int:id>', views.order_detail, name='orderdetail'),
    path('checkout', views.shop_cart_checkout, name='checkout'),
]

order/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import TextInput, ModelForm

from product.models import Product


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product

    @property
    def amount(self):
        return (self.quantity * self.product.price)

class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']
        widgets = {
            'quantity': TextInput(attrs={'class': 'input', 'type': 'number', 'value': '1'}),
        }

class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    surname = models.CharField(max_length=10)
    address = models.CharField(max_length=150)
    city = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    total = models.FloatField()
    note = models.TextField(null=True, default="")
    status = models.CharField(choices=STATUS, default='New', max_length=15)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'surname', 'address', 'city', 'phone']
        widgets = {
            'name': TextInput(attrs={'class': 'input'}),
            'surname': TextInput(attrs={'class': 'input'}),
            'address': TextInput(attrs={'class': 'input'}),
            'city': TextInput(attrs={'class': 'input'}),
            'phone': TextInput(attrs={'class': 'input'}),
        }

class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    total = models.FloatField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render



from order.models import ShopCart, ShopCartForm, OrderDetail, OrderForm, Order


# Create your views here.

@login_required(login_url='/login')
def index(request):
    current_user = request.user
    orders = Order.objects.all().filter(user_id=current_user.id)
    context = {'page': 'orders',
               'orders': orders,
                }
    return render(request, 'order_list.html', context)

@login_required(login_url='/login')
def shop_cart_list(request):
    current_user = request.user
    shopcart = ShopCart.objects.all().filter(user_id=current_user.id)
    carttotal = 0
    for rs in shopcart:
        carttotal += rs.quantity * rs.product.price

    context = {'page': 'cart',
               'shopcart': shopcart,
               'carttotal': carttotal,
              }
    return render(request, 'shop_cart_list.html', context)


@login_required(login_url='/login')
def shop_cart_add(request, proid):
    url = request.META.get('HTTP_REFERER') #BİR ÖNCEKİ ADRESİ ALIR
    form = ShopCartForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            current_user = request.user
            quantity = form.cleaned_data['quantity']

            try:
                q1 = ShopCart.objects.get(user_id=current_user.id, product_id=proid)
            except ShopCart.DoesNotExist:
                q1 = None
            if q1 != None:
                q1.quantity = q1.quantity + quantity
                q1.save()
            else:
                data = ShopCart(user_id=current_user.id, product_id=proid, quantity=quantity)
                data.save()

            request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()
            messages.success(request, "Product added to cart..")
            return HttpResponseRedirect(url)

    return HttpResponseRedirect("/product/"+str(proid)+'/')

@login_required(login_url='/login')
def shop_cart_delete(request, id):
    url = request.META.get('HTTP_REFERER')
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, "Product deleted from cart..")
    return HttpResponseRedirect(url)

@login_required(login_url='/login')
def shop_cart_checkout(request):
    current_user = request.user
    shopcart = ShopCart.objects.all().filter(user_id=current_user.id)
    carttotal = 0
    for rs in shopcart:
        carttotal += rs.quantity * rs.product.price

    form = OrderForm(request.POST or None)
    if request.method == 'POST':

        if form.is_valid():
            data = Order()
            data.name = form.cleaned_data['name']
            data.surname = form.cleaned_data['surname']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.to = form.cleaned_data['name']
            data.user_id = current_user.id
            data.total = carttotal
            data.save()

            for rs in shopcart:
                detail = OrderDetail()
                detail.order_id = data.id
                detail.product_id = rs.product_id
                detail.user_id = current_user.id
                detail.quantity = rs.quantity
                detail.price = rs.product.price
                detail.total = rs.amount
                detail.save()
            ShopCart.objects.filter(user_id=current_user.id).delete()
            request.session['cart_item'] = 0
            messages.success(request, "Order has been completed. Thank you ")
            return HttpResponseRedirect("/order")
    context = {'page': 'checkout',
               'shopcart': shopcart,
               'carttotal': carttotal,
    }

    return  render(request, 'shop_cart_checkout.html', context)

@login_required(login_url='/login')
def order_detail(request,id):

    order = Order.objects.get(pk=id)
    items = OrderDetail.objects.all().filter(order=id)

    context = {'page': 'detail',
               'order': order,
               'items': items,
    }
    return render(request, 'order_detail.html', context)

order/templates/ShopCart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

order/templates/ShopCart_Add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

order/templates/order_detail.html
{% extends "homebase.html" %}
{% load static %}


{% block title %} Shop Cart List {% endblock %}


{% block body %}

    <section id="cart_items">
        <div class="container">
            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/">Home</a></li>
                    <li class="active">Check out</li>
                </ol>
            </div><!--/breadcrums-->

            <div class="col-md-3">
                <div class="table-responsive cart_info">
                    {% include 'user_menu.html' %}
                </div>
            </div>

            <div class="col-md-8">
                <div class="billing-details">
                    <table class="fa-shopping-cart-table table ">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <td>{{ order.name }}</td>
                        </tr>
                        <tr>
                            <th>Surname</th>
                            <td>{{ order.surname }}</td>
                        </tr>
                        <tr>
                            <th>Address</th>
                            <td>{{ order.address }}</td>
                        </tr>
                        <tr>
                            <th>City</th>
                            <td>{{ order.city }}</td>
                        </tr>
                        <tr>
                            <th>Phone</th>
                            <td>{{ order.phone }}</td>
                        </tr>
                        <tr>
                            <th>Date</th>
                            <td>{{ order.create_at }}</td>
                        </tr>
                        <tr>
                            <th>Note</th>
                            <td>{{ order.note }}</td>
                        </tr>
                        <tr>
                            <th>Status</th>
                            <td>{{ order.status }}</td>
                        </tr>
                        </thead>


                        <div class="table-responsive cart_info">
                            <table class="table table-condensed">
                                <thead>
                                <tr class="cart_menu">
                                    <td class="image">Id</td>
                                    <td class="">İnfo</td>
                                    <td class="description">Quantity</td>
                                    <td class="price">Price</td>
                                    <td class="quantity">Tutar</td>

                                    <td></td>
                                </tr>
                                </thead>
                                <tbody>
                                {% for rs in items %}
                                    <tr>
                                        <td class="thumb"><img src="{{ rs.product.image.url }}" alt=""> </td>
                                        <td class="details"><a href="#">{{ rs.product.name }}</a> </td>
                                        <td class="price text-center"><strong>₺ {{ rs.price }}</strong></td>
                                        <td class="qty text-center"><strong>{{ rs.quantity }}</strong></td>
                                        <td class="total text-center"><strong class="primary-color">₺ {{ rs.total }}</strong></td>
                                        <td class="text-right"></td>

                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>


                    </table>
                </div>
            </div>
        </div>
        </div>
    </section>


{% endblock %}

order/templates/order_list.html
{% extends "homebase.html" %}
{% load static %}


{% block title %} Shop Cart List {% endblock %}


{% block body %}


    <section id="cart_items">
        <div class="container">
            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/">Home</a></li>
                    <li class="active">Check out</li>
                </ol>
            </div><!--/breadcrums-->

            <div class="col-md-3">
                <div class="table-responsive cart_info">
                    {% include 'user_menu.html' %}
                </div>
            </div>

            <div class="col-md-9">
                <div class="shopper-informations">

                    {% if messages %}
                        {% for message in messages %}
                            <div class="aler alert-{{ message.tags }}" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <div class="order-summary clearfix">

                        <div class="section-title">
                            <h3 class="title">My Orders</h3>
                        </div>
                        <table class="shopping-cart-table table">
                            <thead>
                            <tr>
                                <th>Name & Surname</th>
                                <th class="text-center">Date</th>
                                <th class="text-center">City</th>
                                <th class="text-center">Phone</th>
                                <th class="text-center">Total</th>
                                <th class="text-center">Status</th>
                                <th class="text-center">Detail</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for rs in orders %}
                                <tr>
                                    <td class="details"><strong>{{ rs.name }} {{ rs.surname }}</strong></td>
                                    <td class="price text-center">{{ rs.create_at }}</td>
                                    <td class="price text-center">{{ rs.phone }}</td>
                                    <td class="qty text-center">{{ rs.city }}</td>
                                    <td class="total text-center"><strong class="primary-color">₺{{ rs.total }}</strong></td>
                                    <td class="total text-center">{{ rs.status }}</td>
                                    <td class="text-right"><a href="/order/detail/{{ rs.id }}"><strong>Detail</strong></a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

order/templates/shop_cart_checkout.html
{% extends "homebase.html" %}
{% load static %}


{% block title %} Shop Cart List {% endblock %}


{% block body %}



    <section id="cart_items">
        <div class="container">
            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/">Home</a></li>
                    <li class="active">Check out</li>
                </ol>
            </div><!--/breadcrums-->

            <div class="col-md-3">
                <div class="table-responsive cart_info">
                    {% include 'user_menu.html' %}
                </div>
            </div>

            <div class="col-md-9">
                <div class="shopper-informations">
                    <div class="row">

                        <div class="col-sm-9 clearfix">
                            <form id="checkout-form" name="order" class="clearfix"  method="post">
                            <div class="bill-to">

                                {% csrf_token %}
                                <div class="form-one">
                                    <p>ORDER DETAILS</p>

                                        <input class="input" type="text" name="name" placeholder="First Name" required id="id_name" value="{{ user.first_name }}">
                                        <input class="input" type="text" name="surname" placeholder="Last Name" required id="id_surname" value="{{ user.last_name }}">
                                        <input class="input" type="text" name="address" placeholder="Address" required id="id_address">
                                        <input class="input" type="text" name="city" placeholder="City" required id="id_city">
                                        <input class="input" type="text" name="phone" placeholder="Telephone" required id="id_phone">

                                </div>

                                <div class="form-two">
                                    <p>BILLING DETAILS</p>

                                        <input type="text" placeholder="Card Holder Name">
                                        <input type="password" placeholder="Card Number">
                                        <input type="text" placeholder="Date mm/yy">
                                        <input type="text" placeholder="Code">
                                        <input type="input" value="Order Total : ₺{{ carttotal }}" readonly>
                                        <button type="submit" class="btn btn-default check_out">Complate Order</button>

                                </div>

                            </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>


            <div class="review-payment">
                <h2>Review & Payment</h2>
            </div>
            <div class="table-responsive cart_info">
                <table class="table table-condensed">
                    <thead>
                    <tr class="cart_menu">
                        <td class="image">Id</td>
                        <td class="">İnfo</td>
                        <td class="description">Quantity</td>
                        <td class="price">Price</td>
                        <td class="quantity">Tutar</td>

                        <td></td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for rs in shopcart %}
                        <tr>
                            <td class="cart_product">
                                <h4>{{ rs.product.id }}</h4>
                            </td>

                            <td class="cart_description">
                                <h4><a href="/product/{{ rs.product.id }}">{{ rs.product.title }}</a></h4>
                                <p>{{ rs.product.description }}</p>
                            </td>

                            <td class="cart_description">
                                <h4><a href="">{{ rs.quantity }}</a></h4>
                                <p></p>
                            </td>
                            <td class="cart_price">
                                <p>{{ rs.product.price }}₺</p>
                            </td>

                            <td class="cart_total">
                                <p class="cart_total_price">{{ rs.amount }}₺</p>
                            </td>
                            <td class="cart_delete">
                                <a class="cart_quantity_delete" href="/order/deletefromcart/{{ rs.id }}"><i
                                        class="fa fa-times"></i></a>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>

        </div>
    </section> <!--/#cart_items-->

{% endblock %}

order/templates/shop_cart_list.html
{% extends "homebase.html" %}
{% load static %}


{% block title %} Shop Cart List {% endblock %}


{% block body %}


    <section id="cart_items">
        <div class="container">
            <div class="breadcrumbs">
                <ol class="breadcrumb">
                    <li><a href="/">Home</a></li>
                    <li class="active">Shopping Cart List</li>
                </ol>
            </div>



            <div>
            {% if messages %}
                {% for message in messages %}
                    <div class="aler alert-{{ message.tags }}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            </div>

            <div class="col-md-3">
                <div class="table-responsive cart_info">
                    {% include 'user_menu.html' %}
                </div>
            </div>



        <div class="col-md-9">
            <div class="table-responsive cart_info">
                <table class="table table-condensed">
                    <thead>
                    <tr class="cart_menu">
                        <td class="image">Id</td>
                        <td class="">İnfo</td>
                        <td class="description">Quantity</td>
                        <td class="price">Price</td>
                        <td class="quantity">Tutar</td>

                        <td></td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for rs in shopcart %}
                        <tr>
                            <td class="cart_product">
                                <h4>{{ rs.product.id }}</h4>
                            </td>

                            <td class="cart_description">
                                <h4><a href="/product/{{ rs.product.id }}">{{ rs.product.title }}</a></h4>
                                <p>{{ rs.product.description }}</p>
                            </td>

                            <td class="cart_description">
                                <h4><a href="">{{ rs.quantity }}</a></h4>
                                <p></p>
                            </td>
                            <td class="cart_price">
                                <p>{{ rs.product.price }}₺</p>
                            </td>

                            <td class="cart_total">
                                <p class="cart_total_price">{{ rs.amount }}₺</p>
                            </td>
                            <td class="cart_delete">
                                <a class="cart_quantity_delete" href="/order/deletefromcart/{{ rs.id }}"><i
                                        class="fa fa-times"></i></a>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>

            <div class="table-responsive cart_info">

                <table class="table table-condensed">
                    <thead>
                    <tr class="cart_menu">
                        <td class="pull-right">Total</td>
                        <td></td>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            <p class="pull-right">{{ carttotal }}₺</p>
                        </td>

                    </tr>
                    </tbody>
                </table>

                <div class="pull-right">
                    <div class="total_area">
                        <a class="btn btn-default check_out" href="/order/checkout">Check Out</a>
                    </div>
                </div>

            </div>
        </div>
        </div>
    </section> <!--/#cart_items-->



{% endblock %}

order/templates/user_menu.html
<div class="cart_menu">
    <h3 class="table-responsive cart_info">User Menu</h3>
</div>


<ul>
    <li><a href="/user/profile"><i class="fa fa-user"></i> My Account</a></li>
    <li><a href="/order/shopcart"><i class="fa fa-shopping-cart"></i> Shop Cart</a></li>
    <li><a href="/order/checkout"><i class="fa fa-crosshairs"></i> Checkout</a></li>
    <li><a href="/order"><i class="fa fa-check"></i> My Orders</a></li>
    <li><a href="/comments"><i class="fa fa-check"></i> My Comments</a></li>
    <li><a href="/logout"><i class="fa fa-lock"></i> Logout</a></li>
</ul>