home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_form),
    path('logout', views.login_out),
    path('contact', views.contact_form, name='contact'),

    path('addcomment/<int:proid>', views.comment_add, name='addcomment'),
    path('deletecomment/<int:id>', views.comment_delete, name='deletecomment'),
    path('comments', views.comment_list, name='comments'),


]

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
   #path('', views.index, name='index'),
    # ex: /product/5/
    path('<int:product_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
    #path('polls/latest.html', views.index),
]

home/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea

from product.models import Product


class Contact(models.Model):
    STATUS = (
        (1, 'New'),
        (2, 'Read'),
    )
    name = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    subject = models.CharField(max_length=100)
    message = models.TextField(max_length=255)
    status = models.IntegerField(choices=STATUS, default=1)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Contact From Message"
        verbose_name_plural = "Contact From Messages"

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name'      : TextInput(attrs={'class': 'input', 'placeholder': 'Name & Surname'}),
            'subject'   : TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'email'     : TextInput(attrs={'class': 'input', 'placeholder': 'Email Address'}),
            'message'   : Textarea(attrs={'class': 'input', 'placeholder': 'Your Message'}),
        }

class Comment(models.Model):
    STATUS = (
        (1, 'True'),
        (0, 'False'),
    )
    RATING = (
        (1,1),
        (2,2),
        (3,3),
        (4,4),
        (5,5),
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    message = models.TextField(max_length=255)
    status = models.IntegerField(choices=STATUS, default=0)
    rating = models.IntegerField(choices=RATING, default=0)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'message', 'rating']
        widgets = {
            'subject': TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'message': TextInput(attrs={'class': 'input', 'placeholder': 'Your review'}),
            'rating': TextInput(attrs={'class': 'input'}),
        }

product/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

# Create your models here.

class Category(models.Model):
    STATUS = (
        (1, 'True'),
        (0, 'False'),
    )
    parent=models.ForeignKey('self',blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    slug = models.SlugField()
    keywords = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    image = models.ImageField(upload_to='images/')
    status = models.IntegerField(choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('slug', 'parent',)
        verbose_name_plural = "categories"

    def __str__(self):
        full_path = [self.title]

        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent

        return ' -> '.join(full_path[::-1])

class Product(models.Model):
    STATUS = (
        (1, 'True'),
        (0, 'False'),
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255, blank=True)
    description = models.CharField(max_length=255, blank=True)
    image = models.ImageField(upload_to='images/')
    price = models.FloatField()
    amount = models.IntegerField()
    detail = RichTextUploadingField()
    status = models.IntegerField(choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_cat_list(self):
        k = self.category
        breadcrumb = ["dummy"]
        while k is not None:
            breadcrumb.append(k.slug)
            k = k.parent
        for i in range(len(breadcrumb)-1):
            breadcrumb[i] = '/'.join(breadcrumb[-1:i-1:-1])
        return breadcrumb[-1:0:-1]

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(blank=True ,upload_to='images/')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

product/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404

# Create your views here.
from home.models import Comment
from product.models import Product, ProductImage


def detail(request, product_id):
        product = get_object_or_404(Product, pk=product_id)
        productimage = ProductImage.objects.filter(product_id=product_id)
        comments = Comment.objects.filter(product=product_id, status=1).order_by('-id')
        #cform = CommentForm()
        context = {'product': product,
                    'productimage': productimage,
                    'comments': comments,
                    #'cform': cform,
        }

        return render(request, 'detail.html', context)

product/templates/detail.html
{% extends "homebase.html" %}


{% block title %}{{ product.title }}{% endblock %}
{% block keywords %}{{ product.keywords }}{% endblock %}
{% block description %}{{ product.description }}{% endblock %}

{% block body %}

    <section>
        <div class="container">
            <div class="row">


                <div class="col-sm-9 padding-center">
                    <div class="product-details"><!--product-details-->
                        <div class="col-sm-5">
                            <div class="view-product">
                                <img src="{{ product.image.url }}" alt=""/>
                                <h3>ZOOM</h3>
                            </div>
                            <div id="similar-product" class="carousel slide" data-ride="carousel">

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner">
                                    <div class="item active">
                                        <a href=""><img src="{{ product.image.url }}" alt=""></a>
                                    </div>
                                    {% for rs in productimage %}
                                        <div class="item">
                                            <a href=""><img src="{{ rs.image.url }}" alt=""></a>

                                        </div>
                                    {% endfor %}

                                </div>

                                <!-- Controls -->
                                <a class="left item-control" href="#similar-product" data-slide="prev">
                                    <i class="fa fa-angle-left"></i>
                                </a>
                                <a class="right item-control" href="#similar-product" data-slide="next">
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>

                        </div>
                        <div class="col-sm-7">
                            <div class="product-information"><!--/product-information-->
                                <img src="images/product-details/new.jpg" class="newarrival" alt=""/>
                                <h2>{{ product.title }}</h2>
                                <p>Product ıd: {{ product.id }}</p>
                                <img src="images/product-details/rating.png" alt=""/>
                                <span>
									<span>{{ product.price }}₺</span>


                                         <div class="product-btns">
                                             <form action="/order/addtocart/{{ product.id }}" method="post">
                                              {% csrf_token %}
                                             <div class="qty-input">

                                                 {{ form.as_p }}

                                              </div>
                                                 <input type="number" value="1"name="quantity"/>
                                                 <button type="submit" class="btn btn-fefault cart"> <i class="primary-btn add-to-cart"></i> Add to Cart</button>
                                             </form>
                                          </div>

								</span>
                                <p><b>Availability:</b> In Stock</p>
                                <p><b>Condition:</b> New</p>
                                <p><b>Brand:</b> E-SHOPPER</p>
                                <a href=""><img src="images/product-details/share.png" class="share img-responsive"
                                                alt=""/></a>
                            </div><!--/product-information-->
                        </div>
                    </div><!--/product-details-->

                    <div class="category-tab shop-details-tab"><!--category-tab-->
                        <div class="col-sm-12">
                            <ul class="nav nav-tabs">
                                <li><a href="#details" data-toggle="tab">Details</a></li>

                                <li class="active"><a href="#reviews" data-toggle="tab">Reviews (5)</a></li>
                            </ul>
                        </div>
                        <div class="tab-content">
                            <div class="tab-pane fade" id="details">
                                <p>{{ product.detail|safe }}</p>
                            </div>


                            <div class="tab-pane fade active in" id="reviews">
                                <div class="col-sm-12">
                                    {% for rs in comments %}
                                    <ul>
                                        <li><a href=""><i class="fa fa-user"></i>{{ rs.user.first_name }}</a></li>
                                        <li><a href=""><i class="fa fa-clock-o"></i>{{ rs.create_at }}</a></li>
                                    </ul>
                                        <p>{{ rs.subject }}</p>
                                        <p>{{ rs.message }}</p>
                                    {% endfor %}

                                    <p><b>Write Your Review</b></p>

                                    <form class="review-form" action="/addcomment/{{ product.id }}" method="post">
                                        {% csrf_token %}
										<span>
											<input class="input" type="text" name="subject" id="id_subject" placeholder="Your Subject"/>
										</span>
                                        <textarea class="input" placeholder="Your review" name="message" id="id_message"></textarea>
                                        <b>Rating: </b>
                                        <div class="stars">
                                            <input type="radio" id="star5" name="rating" value="5"/><label for="star5"></label>
                                            <input type="radio" id="star4" name="rating" value="4"/><label for="star4"></label>
                                            <input type="radio" id="star3" name="rating" value="3"/><label for="star3"></label>
                                            <input type="radio" id="star2" name="rating" value="2"/><label for="star2"></label>
                                            <input type="radio" id="star1" name="rating" value="1"/><label for="star1"></label>
                                        </div>
                                        <button class="btn btn-default pull-right">Submit</button>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div><!--/category-tab-->


                </div>
            </div>
        </div>
    </section>


{% endblock %}